### ISSUE TITLE
Token.public not being found

### ISSUE THREAD

**Issue by Phanstar0** [assetto-corsa-web/accweb#22]
This is my first time trying your server tool so im not sure if I'm doing correctly or not. And sorry if this is overly detailed. Just want to make sure all relevent info is given.

I created the "secrets" folder in the accweb_1.4.0 folder and then generated public and private keys and put them in their own text documents. Then named them accordingly ("token.public" and "token.private"). After following the rest of the instructions I open a CMD window and go the the accweb1.4.0 folder and type the command "start.cmd". At the end of the command prompt it says 

time="2019-10-08T20:02:30-04:00" level=fatal msg="Token public key file not found" err="open secrets/token.public: The system cannot find the file specified." file="secrets/token.public"

I've deleted them and recreated the folder and tokens multiple times but I still get the same error message.

**Comment by Kugelschieber** [comment]
Can you try changing the variables in start.cmd to absolute paths and check file permissions? For example:
```
Rem these files must exist
set ACCWEB_TOKEN_PUBLIC_KEY=C:/accweb/secrets/token.public
set ACCWEB_TOKEN_PRIVATE_KEY=C:/accweb/secrets/token.private
```

**Comment by Phanstar0** [comment]
Thank you for your advice. I was able to solve the problem. I really had to be specific with the absolute path and add .txt to the end in start.cmd. Not sure if you or anyone else had to do that but I usually seem to be the odd one out with these things. Thanks again.

**Comment by Menteroth** [comment]
For future reference it's because you opened it in Notepad, I am guessing, and then just saving it as a text file. Then it adds `.txt` to the end even if you have a . in the name somewhere. You need to change to `all files` before you save and then you can have whatever lastname for the file you want and it will be saved like that.

So `token.public` would be just that with no `.txt` at the end when you save it.
